application: s~molly-123
#application: e~testeu123
version: rpc-1
runtime: python27
api_version: 1
threadsafe: no

inbound_services:
- warmup
- mail_bounce

builtinsa:
- deferred: on
- remote_api: on

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "latest"
- name: PIL
  version: "latest"

handlers:
#- url: .*
#  script: bquery.app
#  login: optional

- url: /.*
  script: main.app
  login: required
