#application: s~molly-123

application: s~beaming-team-327
#application: e~testeu123
version: rpc-1
runtime: python27
api_version: 1
threadsafe: no

inbound_services:
- warmup
- mail_bounce

builtins:
- deferred: on
- remote_api: on

env_variables:
  GAE_USE_SOCKETS_HTTPLIB : 'true'

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "latest"
- name: PIL
  version: "latest"

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /css
  static_dir: css

#- url: .*
#  script: bquery.app
#  login: optional
- url: /rpc.*
  script: rpc.app

- url: /_ah/bounce
  script: handle_bounced_email.app
  login: admin

- url: /.*
  script: main.app
  login: required
